version: "3"

services:
  deltalake:
    image: deltaio/delta-docker:latest_arm64
    platform: linux/arm64
    hostname: dl-hitchhikers_guide
    container_name: dl-hitchhikers_guide
    environment:
      - SPARK_LOCAL_HOSTNAME=localhost
    volumes:
      - ${PWD}:/opt/spark/work-dir/hitchhikers_guide
    ports:
      - 8888-8889:8888-8889
    restart: always
